//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class studentlearnEntities1 : DbContext
    {
        public studentlearnEntities1()
            : base("name=studentlearnEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<quiz> quizs { get; set; }
        public virtual DbSet<userrate> userrates { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
