//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public int id { get; set; }
        public string questionName { get; set; }
        public string questionText { get; set; }
        public string reply { get; set; }
        public string reply1 { get; set; }
        public string reply2 { get; set; }
        public string reply3 { get; set; }
        public string reply4 { get; set; }
        public int categoryID { get; set; }
    }
}
